### ISSUE TITLE
Hide terminal window on Windows

### ISSUE THREAD

**Issue by joreiff** [jsoncomma/sublime-jsoncomma#11]
On Windows, the new subprocess-based implementation causes a terminal window to show up. This can be avoided by appropriately setting the `startupinfo` argument of `subprocess.Popen`. See https://stackoverflow.com/a/1016651 for a full example.

**Comment by math2001** [comment]
Oh yes I forgot about that. I'm doing all the testing on Linux now. That should be an easy fix, especially with your help. If you wanna send a PR, feel free :slightly_smiling_face: Otherwise I'll implement this today.

**Comment by joreiff** [comment]
Thanks for your fast response!

**Comment by math2001** [comment]
The changes are pushed, but not released yet (you'll still have those really annoying windows in your text editor, i'm sorry about that), because it would cause more issues with #10. Everything will be live once #10 is fixed though.
