### ISSUE TITLE
life management of the server

### ISSUE THREAD

**Issue by math2001** [jsoncomma/sublime-jsoncomma#12]
Because we can't kill the server on exit, JSONComma creates a bunch of zombie processes...

That's a problem in itself, but also prevents automatic updates.

So, JSONComma should kill the server once there are no windows left (that's the best it can do). Since it is allowed for the sublime text process to be running without any window, that'll mean that some a `pre_save` listener might be triggered *without any server running*. So, that means that *each* listener should make sure that the server is running. If not, it should start it asynchronously, and give up on trying to fix the current JSON file.

Trick: maybe we can do that in `ViewEventListener.is_applicable`

**Comment by math2001** [comment]
Actually, this doesn't even work, the `on_close` listener is not run when it messes around with subprocess stuff. I don't understand why, but it too close to the "black box boundary" of sublime text for it to worth investigating I think.

So, instead, JSONComma always uses the same port (2442, the reason is in the git logs of jsoncomma), and start the server if it doesn't reply. If it does, then we assume that it's our server. When sublime text exits, then the server might keep on going, there's nothing we can do about that.

When the server needs to be explicitly closed (the only case right now is when we need to update the binary), then we send a `/shutdown` requests, which takes at most 2 seconds to complete (that's controlled by the server, talking from https://github.com/jsoncomma/jsoncomma/commit/ee54655c3ab26494db7d4c3c8a8616d211755e5b). 1 second to wait for all handlers to "complete", and 1 second to `server.Shutdown` (that should never be a problem).

**Comment by math2001** [comment]
Fixed by 3226c60

**Comment by TerminalFi** [comment]
ST4 implements `on_exit` this should be updated, but breaks backwards compatibility

**Comment by math2001** [comment]
I could implement two different behavior, depending on the ST version. However, it will add an other layer of complexity to support both version. I'll definitely use it once ST4 becomes the standard. But I doubt I'll support both versions.
