### ISSUE TITLE
Autoupdate saving executable to configuration folder

### ISSUE THREAD

**Issue by WillMoggridge** [jsoncomma/sublime-jsoncomma#15]
By default on Linux, this tool is saving the executable to `$HOME/.config/jsoncomma/jsoncomma` which is inside a directory designed for configuration.
I would prefer not to save executables there but would like to use autoupdate.

Would it be possible to change where it saves, or I'd be happy being able to define it manually in the configuration.

---

If there is interest in defining a better default location, I would direct to the XDG directory specifications
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

I believe the data directory could be the best use for this. Ideally checking to see if a `XDG_DATA_HOME` environment variable exists. If it does not, falling back to `.local/share`.

I'm not exactly an expert on this though, someone may have a better solution.

This extension has saved me sanity at times, so thank you! :)

**Comment by math2001** [comment]
> Would it be possible to change where it saves, or I'd be happy being able to define it manually in the configuration.

The better option would definitely be to change where it saves by default. Adding a config option is just always more work for the user and the dev, so if it can be avoided (math2001/FileManager#53).

> I believe the data directory could be the best use for this. Ideally checking to see if a XDG_DATA_HOME environment variable exists. If it does not, falling back to .local/share.

I agree, I'll do that.

> This extension has saved me sanity at times, so thank you! :)

:slightly_smiling_face:
