### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by lifesign** [jsoncomma/sublime-jsoncomma#16]
got another error after reinstall latest plugin.

![image](https://user-images.githubusercontent.com/2189610/72660253-2567dd00-3a06-11ea-9274-ee549756e393.png)

JsonComma Plugin Version: 0.2.7
![image](https://user-images.githubusercontent.com/2189610/72660256-2bf65480-3a06-11ea-91a8-780c4c6515ce.png)

Sublime Text Version: Build 4062

btw, would jsoncomma cli can have --help option? i can't verify it's version though i know it should be the latest version

![image](https://user-images.githubusercontent.com/2189610/72660275-8ee7eb80-3a06-11ea-87bf-eadf2e51ffa7.png)

**Comment by math2001** [comment]
No that should work (the `./jsoncomma -h`). How did you install the binary? Was it done automatically?

Can you check the file size of jsoncomma (`ls -l jsoncomma`) please?

An exec error probably means that you have the wrong binary installed (ie the wrong platform), or maybe the file is corrupted. Maybe it's empty.

**Comment by lifesign** [comment]
I reinstalled both jsoncomma binary and Sublime plugin, it's works now~
I think maybe the previous file is corrupted

![image](https://user-images.githubusercontent.com/2189610/72679516-e19ad380-3aea-11ea-9de4-86467791b003.png)

Failed on first try
![image](https://user-images.githubusercontent.com/2189610/72679520-e8c1e180-3aea-11ea-8cd5-ba0e87930909.png)

Seems OK 
![image](https://user-images.githubusercontent.com/2189610/72679524-f2e3e000-3aea-11ea-9d02-c360f8d4a8a4.png)

![image](https://user-images.githubusercontent.com/2189610/72679525-f5ded080-3aea-11ea-91f5-153b02dddbd1.png)

**Comment by math2001** [comment]
That's weird...

>  it's works now~

Alright, I'll close this issue then.

> I think maybe the previous file is corrupted

Yep, that'd be my best guess... Maybe sublime-jsoncomma should validate the download with the checksum provided on GitHub. I don't think I'll get around to doing that soon, but I'll track that in a new issue.
