### ISSUE TITLE
Issue: truncates large files

### ISSUE THREAD

**Issue by CurtisHumphrey** [jsoncomma/sublime-jsoncomma#20]
On large JSON files (more than 4k characters), it appears to be truncating it to around 4096 characters.  Does it have something to do with the package size being sent to the server?

**Comment by jamesmoss** [comment]
I've had to disable the plugin currently due to this bug. Its pretty major.

**Comment by hsmyers** [comment]
Thank heavens you can recover (in my case) a great deal of the missing file by Cntrl-Z-ing! Still lost about 4 hours work. Great plug-in, but this bug has got to go!!

**Comment by Aub-C** [comment]
Same bug for me. I had to remove several plugins to figure out which was the culprit. I found that you can switch from JSON to Plain Text to save the file. However, I just uninstalled the plugin until this can be fixed.

**Comment by sinahwz** [comment]
Same issue. super useful plugin, but had to disable it

**Comment by fatmarker** [comment]
Just experienced this as well.

**Comment by nexeh** [comment]
@fatmarker thank you for responding to my post in Sublime forums and linking me here. Its nice to see the picture get clearer! It was a frustrating situation for me and im sure others.

**Comment by Heiner92** [comment]
same situation for me. I spent half an hour searching for the buggy package and lost hours of work because my json-file was shortened from 4k lines to 140 lines...
I would really like to have the functionality of this package but this issue needs to be fixed first!

**Comment by Heiner92** [comment]
For anybody who is interested in a fix:
I have found a solution for this issue. See the pull-request in the jsoncomma server repo [https://github.com/jsoncomma/jsoncomma/pull/4](https://github.com/jsoncomma/jsoncomma/pull/4)
Everybody who knows Go better than me, feel free to enhance this fix to use the actual json-size as the new buffer-max-size

**Comment by math2001** [comment]
I pushed a new a version, it should fix this issue (it does on my end at least) (the sublime plugin will automatically update the binary for you). I'll close this. Reopen if the bug still occurs on your end.
