### ISSUE TITLE
Can help to port to Cudatext?

### ISSUE THREAD

**Issue by Alexey-T** [jsoncomma/sublime-jsoncomma#4]
Can you help to port plugin? what I need to port:

- separate "def" which can do comma work inside string (string with EOLs) -
```
def handle_commas(s):
  pass
```
If you can make this func, and use this func in ST3 plugin, it is easy to port

**Comment by math2001** [comment]
As I told you earlier, this plugin uses the scope (the syntax highlighting) of Sublime Text, and it's specific API to add/remove commas. So, I can't write a function that would work on its own that would do the job properly.

**Comment by Alexey-T** [comment]
OK, but such code is strange..
