### ISSUE TITLE
Support for additional extensions

### ISSUE THREAD

**Issue by notiv-nt** [jsoncomma/sublime-jsoncomma#5]
For example, i have file `config.json5` (http://json5.org/), and how i can use this plugin with this extension ?

**Comment by math2001** [comment]
Why do you need this for JSON5? It supports trailing commas... 🤔

**Comment by WillMoggridge** [comment]
To add a use case, I just tried using this language to improve syntax highlighting:
https://packagecontrol.io/packages/JSON%20Key-Value

It seems like this extension doesn't work with that language and I am unable to configure it to. I would really love to use both together! :smile:
