### ISSUE TITLE
Doesn't add comma when a line finishes with a number

### ISSUE THREAD

**Issue by dortamiguel** [jsoncomma/sublime-jsoncomma#6]
Thanks for this fantastic plugin.

I found that it doesn't add a comma when a line finishes with a number

``` json
{
    "comma will be added at the of this line": "test"
    "comma not added when is a number": 5
    "something": "something"
}
```

**Comment by math2001** [comment]
That's fixed with the new [`jsoncomma`](https://jsoncomma.github.io) :tada:
