### ISSUE TITLE
breaking change ?

### ISSUE THREAD

**Issue by lifesign** [jsoncomma/sublime-jsoncomma#7]
hi, used jsoncomma for a long time, this is an awesome plugin, appreciate it.
but today i open my st3 , a window popup, it seems this plugin was being refactoring ? 

![image](https://user-images.githubusercontent.com/2189610/72220016-4acc9500-3587-11ea-849e-ff89358c080a.png)
it failed when i try to download by plugin

ST Version: 3.2.2 Build 3211
in sublime console
```
reloading settings Packages/User/Preferences.sublime-settings
JSONComma: downloading binary from https://github.com/jsoncomma/jsoncomma/releases/download/v0.1.2/jsoncomma_v0.1.2_Darwin_x86_64.tar.gz
Package Control: Skipping automatic upgrade, last run at 2020-01-12 21:34:07, next run at 2020-01-12 22:34:07 or after
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "/Users/lifesign/Library/Application Support/Sublime Text 3/Installed Packages/JSONComma.sublime-package/server.py", line 50, in start
  File "/Users/lifesign/Library/Application Support/Sublime Text 3/Installed Packages/JSONComma.sublime-package/server.py", line 209, in download
KeyError: 'osx'
```

**Comment by lifesign** [comment]
May be this is the reason? 

`server.py` line 168 use `os x` for key
<img width="769" alt="Jietu20200112-221008@2x" src="https://user-images.githubusercontent.com/2189610/72220135-861b9380-3588-11ea-8daf-2b6db5a0925a.png">

<img width="702" alt="Jietu20200112-221024" src="https://user-images.githubusercontent.com/2189610/72220146-a3506200-3588-11ea-9372-71ba2047c707.png">

on my mac os, sublime console's output is  `osx` not `os x`

```
>>> sublime.platform()
'osx'
```

Mac OS Version: 10.14.6

**Comment by math2001** [comment]
Damn it. Yes that's exactly it @lifesign, thank you for the detailed error report. Sorry for that :slightly_frowning_face:
