### ISSUE TITLE
Command Palette Error

### ISSUE THREAD

**Issue by lifesign** [jsoncomma/sublime-jsoncomma#8]
already checked  [this issue](https://github.com/jsoncomma/sublime-jsoncomma/issues/7) it's working now, thx

the plugin works well, but i got this error when i open Command Palette
![image](https://user-images.githubusercontent.com/2189610/72231174-d92b3000-35f4-11ea-9d94-88cf6379bbb5.png)

**Comment by math2001** [comment]
Oh yep, I didn't see that one. Thanks a bunch for reporting! :slightly_smiling_face: 

By the way, how do you get this warning in the status bar? I'd use that.

**Comment by lifesign** [comment]
I'm using Guna theme 😊
https://packagecontrol.io/packages/Guna
